USE [master]
GO
CREATE DATABASE [FleetManagerDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FleetManagerDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FleetManagerDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FleetManagerDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\FleetManagerDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [FleetManagerDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FleetManagerDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FleetManagerDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FleetManagerDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FleetManagerDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FleetManagerDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FleetManagerDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FleetManagerDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FleetManagerDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FleetManagerDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FleetManagerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FleetManagerDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FleetManagerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FleetManagerDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FleetManagerDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FleetManagerDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FleetManagerDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FleetManagerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FleetManagerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FleetManagerDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FleetManagerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FleetManagerDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FleetManagerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FleetManagerDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FleetManagerDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FleetManagerDB] SET  MULTI_USER 
GO
ALTER DATABASE [FleetManagerDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FleetManagerDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FleetManagerDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FleetManagerDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FleetManagerDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FleetManagerDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FleetManagerDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [FleetManagerDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FleetManagerDB]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Clearance](
    [ClearanceId] [int] NOT NULL,
    [ClearanceLevel] [int] NOT NULL,
    [Description] [varchar](500) NOT NULL,
 CONSTRAINT [PK_Clearance] PRIMARY KEY CLUSTERED 
(
    [ClearanceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CustomField](
    [CustomFieldId] [int] IDENTITY(1,1) NOT NULL,
    [TenantId] [int] NOT NULL,
    [ValueTypeId] [int] NOT NULL,
    [FieldName] [varchar](500) NOT NULL,
    [IsDeleted] [bit] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_CustomField] PRIMARY KEY CLUSTERED 
(
    [CustomFieldId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[CustomFieldValue](
    [CustomFieldValueId] [int] IDENTITY(1,1) NOT NULL,
    [VehicleId] [int] NOT NULL,
    [CustomFieldId] [int] NOT NULL,
    [Value] [sql_variant] NOT NULL,
    [IsDeleted] [bit] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_CustomFieldValue] PRIMARY KEY CLUSTERED 
(
    [CustomFieldValueId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[FuelType](
    [FuelTypeId] [int] NOT NULL,
    [FuelTypeName] [varchar](500) NOT NULL,
    [IsDeleted] [bit] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_FuelType] PRIMARY KEY CLUSTERED 
(
    [FuelTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Tenant](
    [TenantId] [int] IDENTITY(1,1) NOT NULL,
    [CompanyName] [varchar](50) NOT NULL,
    [VATNumber] [varchar](11) NOT NULL,
    [IsDeleted] [bit] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_Tenant] PRIMARY KEY CLUSTERED 
(
    [TenantId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[User](
    [UserId] [int] IDENTITY(1,1) NOT NULL,
    [TenantId] [int] NOT NULL,
    [UserName] [varchar](500) NOT NULL,
    [Password] [varchar](500) NOT NULL,
    [Email] [varchar](500) NOT NULL,
    [ClearanceId] [int] NOT NULL,
    [IsDeleted] [bit] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
    [UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Vehicle](
    [VehicleId] [int] IDENTITY(1,1) NOT NULL,
    [TenantId] [int] NOT NULL,
    [VehicleTypeId] [int] NOT NULL,
    [Brand] [varchar](500) NOT NULL,
    [Model] [varchar](500) NOT NULL,
    [ChassisNumber] [varchar](500) NOT NULL,
    [LicensePlate] [varchar](500) NOT NULL,
    [FuelTypeId] [int] NOT NULL,
    [Color] [varchar](500) NULL,
    [IsDeleted] [bit] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_Vehicle] PRIMARY KEY CLUSTERED 
(
    [VehicleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[VehicleType](
    [VehicleTypeId] [int] NOT NULL,
    [TypeName] [varchar](500) NOT NULL,
    [isDeleted] [bit] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_VehicleType] PRIMARY KEY CLUSTERED 
(
    [VehicleTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CustomField]  WITH CHECK ADD  CONSTRAINT [FK_CustomField_Tenant] FOREIGN KEY([TenantId])
REFERENCES [dbo].[Tenant] ([TenantId])
GO
ALTER TABLE [dbo].[CustomField] CHECK CONSTRAINT [FK_CustomField_Tenant]
GO
ALTER TABLE [dbo].[CustomFieldValue]  WITH CHECK ADD  CONSTRAINT [FK_CustomFieldValue_CustomField] FOREIGN KEY([CustomFieldId])
REFERENCES [dbo].[CustomField] ([CustomFieldId])
GO
ALTER TABLE [dbo].[CustomFieldValue] CHECK CONSTRAINT [FK_CustomFieldValue_CustomField]
GO
ALTER TABLE [dbo].[CustomFieldValue]  WITH CHECK ADD  CONSTRAINT [FK_CustomFieldValue_Vehicle] FOREIGN KEY([VehicleId])
REFERENCES [dbo].[Vehicle] ([VehicleId])
GO
ALTER TABLE [dbo].[CustomFieldValue] CHECK CONSTRAINT [FK_CustomFieldValue_Vehicle]
GO
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_Clearance] FOREIGN KEY([ClearanceId])
REFERENCES [dbo].[Clearance] ([ClearanceId])
GO
ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_Clearance]
GO
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_Tenant] FOREIGN KEY([TenantId])
REFERENCES [dbo].[Tenant] ([TenantId])
GO
ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_Tenant]
GO
ALTER TABLE [dbo].[Vehicle]  WITH CHECK ADD  CONSTRAINT [FK_Vehicle_FuelType] FOREIGN KEY([FuelTypeId])
REFERENCES [dbo].[FuelType] ([FuelTypeId])
GO
ALTER TABLE [dbo].[Vehicle] CHECK CONSTRAINT [FK_Vehicle_FuelType]
GO
ALTER TABLE [dbo].[Vehicle]  WITH CHECK ADD  CONSTRAINT [FK_Vehicle_Tenant] FOREIGN KEY([TenantId])
REFERENCES [dbo].[Tenant] ([TenantId])
GO
ALTER TABLE [dbo].[Vehicle] CHECK CONSTRAINT [FK_Vehicle_Tenant]
GO
ALTER TABLE [dbo].[Vehicle]  WITH CHECK ADD  CONSTRAINT [FK_Vehicle_VehicleType] FOREIGN KEY([VehicleTypeId])
REFERENCES [dbo].[VehicleType] ([VehicleTypeId])
GO
ALTER TABLE [dbo].[Vehicle] CHECK CONSTRAINT [FK_Vehicle_VehicleType]
GO
USE [master]
GO
ALTER DATABASE [FleetManagerDB] SET  READ_WRITE 
GO 